### PR TITLE
Add feature : cost per weight

### PR DESCRIPTION
**Pull request by Pinaute**
Hi,
The feature display a cost estimate based on the filament weigh and display units.
I developed this feature because I know the cost of each roll and weight, but not the cost per meter.
I know a issue : the state of the checkbox (to select the cost.) is not saved, so if the page is reloaded the checkbox returns to the default value. This issue does not prevent the work program.

Thanks, Antoine

### CODE REVIEW

**Comment by jasiek** [comment]
Can you squash these to 1 commit?

**Comment by Pinaute** [comment]
I squash my last five commits together into one commit,  I have run following command

    $ git rebase -i HEAD~5

**Comment by jasiek** [comment]
Hey,

I need some time to test this. I'll get back to you.

**Comment by cnelsonsic** [comment]
Would just like to bump this PR since I need it as well.

**Pull request merged**
